version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package
      - sam package
        --template-file template.yml
        --output-template-file packaged-template.yml
  artifacts:
    files:
      - packaged-template.yml